# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 040c93c90afcaa98b509dbecddc4e299dfe38286556adbf5d62fdcb38e55dd971acfda3c5a886d46cf80b647340ad87ccedd7c24ac798dfc7a0847cc20d9c3c8

test:
  secret_key_base: cad912e8b74929af15ce28330b8c19df627020c1b3a5857a4c9478965408fd5a971de78af98547a56508b31dc1e1c528746f666608dc71dfb61e0eb4b29158b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
